# Generated by Django 5.2.17 on 2026-09-07 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Retro",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("participant_limit", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pin_hash", models.CharField(max_length=128)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("writing", "Writing"),
                            ("revealed", "Revealed"),
                            ("voting", "Voting"),
                            ("discussing", "Discussing"),
                            ("closed", "Closed"),
                        ],
                        default="writing",
                        max_length=20,
                    ),
                ),
                ("timer_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("timer_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timer_paused_remaining_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
